version: '2'
services:
  simulavr:
    build: .
    container_name: simulavr
    image: simulavr-img
    volumes:
      - ./avr-project:/avr-project
    working_dir: /avr-project
    stdin_open: true # docker run -i
    tty: true        # docker run -t